# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from factorforge.interop.lean import lean_pb2 as factorforge_dot_interop_dot_lean_dot_lean__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in factorforge/interop/lean/lean_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeanVerifierStub:
    """FactorForge wraps the LEAN launcher; this is not an upstream LEAN service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/factorforge.lean.v1.LeanVerifier/Health',
                request_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthRequest.SerializeToString,
                response_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Capabilities = channel.unary_unary(
                '/factorforge.lean.v1.LeanVerifier/Capabilities',
                request_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.VerifyStrategy = channel.unary_unary(
                '/factorforge.lean.v1.LeanVerifier/VerifyStrategy',
                request_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyRequest.SerializeToString,
                response_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyResponse.FromString,
                _registered_method=True)


class LeanVerifierServicer:
    """FactorForge wraps the LEAN launcher; this is not an upstream LEAN service.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeanVerifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthRequest.FromString,
                    response_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthResponse.SerializeToString,
            ),
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesRequest.FromString,
                    response_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'VerifyStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyStrategy,
                    request_deserializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyRequest.FromString,
                    response_serializer=factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factorforge.lean.v1.LeanVerifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('factorforge.lean.v1.LeanVerifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeanVerifier:
    """FactorForge wraps the LEAN launcher; this is not an upstream LEAN service.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factorforge.lean.v1.LeanVerifier/Health',
            factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthRequest.SerializeToString,
            factorforge_dot_interop_dot_lean_dot_lean__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factorforge.lean.v1.LeanVerifier/Capabilities',
            factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesRequest.SerializeToString,
            factorforge_dot_interop_dot_lean_dot_lean__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factorforge.lean.v1.LeanVerifier/VerifyStrategy',
            factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyRequest.SerializeToString,
            factorforge_dot_interop_dot_lean_dot_lean__pb2.VerifyStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
